enum AuditAction {
  CALCULATION_CREATED = 'CALCULATION_CREATED',
  MANUAL_CALCULATION_CREATED = 'MANUAL_CALCULATION_CREATED',
  MANUAL_CALCULATION_FAILED = 'MANUAL_CALCULATION_FAILED',
  CALCULATION_FAILED = 'CALCULATION_FAILED',
  BULK_COMPARISON_CREATED = 'BULK_COMPARISON_CREATED',
  BULK_COMPARISON_FAILED = 'BULK_COMPARISON_FAILED',
  GENUINE_OVERRIDE_CREATED = 'GENUINE_OVERRIDE_CREATED',
  GENUINE_OVERRIDE_FAILED = 'GENUINE_OVERRIDE_FAILED',
}

export default AuditAction
