enum AuditAction {
  CALCULATION_CREATED = 'CALCULATION_CREATED',
  MANUAL_CALCULATION_CREATED = 'MANUAL_CALCULATION_CREATED',
  MANUAL_CALCULATION_FAILED = 'MANUAL_CALCULATION_FAILED',
  CALCULATION_FAILED = 'CALCULATION_FAILED',
}

export default AuditAction
