enum AuthorisedRoles {
  ROLE_RELEASE_DATES_CALCULATOR = 'ROLE_RELEASE_DATES_CALCULATOR',
  ROLE_RELEASE_DATE_COMPARER = 'ROLE_RELEASE_DATE_COMPARER',
  ROLE_RELEASE_DATE_MANUAL_COMPARER = 'ROLE_RELEASE_DATE_MANUAL_COMPARER',
  ROLE_CRDS_SPECIALIST_SUPPORT = 'ROLE_CRDS_SPECIALIST_SUPPORT',
  ROLE_INACTIVE_BOOKINGS = 'ROLE_INACTIVE_BOOKINGS',
}

export default AuthorisedRoles
