enum AuthorisedRoles {
  ROLE_RELEASE_DATES_CALCULATOR = 'ROLE_RELEASE_DATES_CALCULATOR',
  ROLE_RELEASE_DATE_COMPARER = 'ROLE_RELEASE_DATE_COMPARER',
  ROLE_RELEASE_DATE_MANUAL_COMPARER = 'ROLE_RELEASE_DATE_MANUAL_COMPARER',
  ROLE_CRDS_SPECIALIST_SUPPORT = 'ROLE_CRDS_SPECIALIST_SUPPORT',
  ROLE_CRDS_GENUINE_OVERRIDES = 'ROLE_CRD__GENUINE_OVERRIDES__RO',
  ROLE_INACTIVE_BOOKINGS = 'ROLE_INACTIVE_BOOKINGS',
  ROLE_COURTCASE_RELEASEDATE_SUPPORT = 'ROLE_COURTCASE_RELEASEDATE_SUPPORT',
}

export default AuthorisedRoles
