enum CalculationRule {
  HDCED_GE_MIN_PERIOD_LT_MIDPOINT = 'HDCED_GE_MIN_PERIOD_LT_MIDPOINT',
  HDCED_GE_MIDPOINT_LT_MAX_PERIOD = 'HDCED_GE_MIDPOINT_LT_MAX_PERIOD',
  HDCED_MINIMUM_CUSTODIAL_PERIOD = 'HDCED_MINIMUM_CUSTODIAL_PERIOD',
  TUSED_LICENCE_PERIOD_LT_1Y = 'TUSED_LICENCE_PERIOD_LT_1Y',
  LED_CONSEC_ORA_AND_NON_ORA = 'LED_CONSEC_ORA_AND_NON_ORA',
}

export default CalculationRule
