import { components } from './index'

export type BookingCalculation = components['schemas']['CalculatedReleaseDates']
export type WorkingDay = components['schemas']['WorkingDay']
export type CalculationBreakdown = components['schemas']['CalculationBreakdown']
export type DateBreakdown = components['schemas']['DateBreakdown']
export type ValidationMessage = components['schemas']['ValidationMessage']
export type ReleaseDateCalculationBreakdown = components['schemas']['ReleaseDateCalculationBreakdown']
export type CalculationFragments = components['schemas']['CalculationFragments']
export type CalculationUserQuestions = components['schemas']['CalculationUserQuestions']
export type CalculationSentenceQuestion = components['schemas']['CalculationSentenceQuestion']
export type CalculationUserInputs = components['schemas']['CalculationUserInputs']
export type CalculationSentenceUserInput = components['schemas']['CalculationSentenceUserInput']
export type CalculationResults = components['schemas']['CalculationResults']
export type SubmittedDate = components['schemas']['SubmittedDate']
export type ManualEntryDate = components['schemas']['ManualEntrySelectedDate']
export type SubmitCalculationRequest = components['schemas']['SubmitCalculationRequest']
export type GenuineOverride = components['schemas']['GenuineOverrideResponse']
export type GenuineOverrideDateRequest = components['schemas']['GenuineOverrideDateRequest']
export type GenuineOverrideDateResponse = components['schemas']['GenuineOverrideDateResponse']
export type NonFridayReleaseDay = components['schemas']['NonFridayReleaseDay']
