---
# Per environment values which override defaults in calculate-release-dates/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: calculate-release-dates-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://calculate-release-dates-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_API_URL: "https://calculate-release-dates-api-preprod.hmpps.service.justice.gov.uk"
    PRISON_API_URL: "https://api-preprod.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-offender-search-preprod.prison.service.justice.gov.uk"
    DIGITAL_PRISON_SERVICES_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    VIEW_JOURNEY_FEATURE_TOGGLE: "false"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
