---
# Per environment values which override defaults in calculate-release-dates/values.yaml

generic-service:

  ingress:
    host: calculate-release-dates-alt-preprod.hmpps.service.justice.gov.uk
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine DetectionOnly
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level=2"

  env:
    INGRESS_URL: "https://calculate-release-dates-alt-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_API_URL: "https://calculate-release-dates-api-alt-preprod.hmpps.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    DIGITAL_PRISON_SERVICES_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    SDS_EXCLUSION_INDICATORS_ENABLED: "false"
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    COURT_CASES_AND_RELEASE_DATES_URL: "https://court-cases-release-dates-preprod.hmpps.service.justice.gov.uk"
    FRONTEND_COMPONENT_API_TIMEOUT: 500
    CALCULATE_RELEASE_DATES_API_TIMEOUT_RESPONSE: 60000
    CALCULATE_RELEASE_DATES_API_TIMEOUT_DEADLINE: 60000
    HDC4_PLUS_COMPARISON_TAB_ENABLED: "true"
    PRINT_NOTIFICATION_SLIP_ENABLED: "true"
    HDC4_BANNER_ENABLED: "true"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    SHOW_BREAKDOWN: "true"
    SDS40_POLICY_SUPPORTED: "OFF"

generic-prometheus-alerts:
  targetApplication: calculate-release-dates-alt-preprod
  businessHoursOnly: true
  alertSeverity: legacy-replacement-alerts-non-prod
